sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t wesreisz/docker-react-v1 -f Dockerfile.dev .

script:
  - docker run -e CI=true wesreisz/docker-react-v1 npm run test